### ISSUE TITLE
Add 18F Analytics ID

### ISSUE THREAD

**Issue by jstrothman** [18F/agile#112] opened 2020-08-14 13:02 UTC
The Agile Guide sends visit data to DAP, which is great for gov aggregate tracking and has some useful reports for 18F as well. For more detailed reporting, agencies also use their own Google Analytics ID.
Each 18F Guide (as well as the handbook, methods, and a few other sites use the GA ID: UA-48605964-19 -- we can use this for aggregate tracking across these sites, and we have filtered GA 'views' so teams can interrogate the data for a particular guide or site. 

To add the GA ID to the site, in /_config.yml, just as you have `dap_agency`, add `google_analytics_ua: UA-48605964-19` 

**Acceptance Criteria**
- [ ] The site sends data to the GA 18F Account > Microsites Property (can test using the Chrome plugin Tag Assistant)

**Comment by ryanwoldatwork** [comment] 2020-09-15 15:57
https://github.com/18F/agile/pull/114

![analytics](https://user-images.githubusercontent.com/64987852/93234780-909eb600-f731-11ea-9d5e-ebe0d387c25a.png)

**Comment by ryanwoldatwork** [comment] 2021-10-08 18:32
This issue can be closed. The site now has a DAP tag.

view-source:https://agile.18f.gov/

**Comment by cannandev** [comment] 2022-07-28 18:00
Closing this issue since it has been confirmed.

**Closed as completed by cannandev** 2022-07-28 18:00 UTC
