### ISSUE TITLE
Update favicon for the Agile Guide

### ISSUE THREAD

**Issue by allalala** [18F/agile#52] opened 2018-07-03 17:11 UTC
![image](https://user-images.githubusercontent.com/6518236/42234431-8b37fa76-7ec2-11e8-9e64-c999bb9e8c36.png)

**Comment by porta-antiporta** [comment] 2018-07-25 16:03
Root cause to an old gem being used for the 18f-style-guide. h/t @stvnrlly.

Working through it, but to rebuild using newer gems have to first upgrade my version of Ruby, which is proving...challenging.

**Comment by porta-antiporta** [comment] 2018-07-26 20:31
resolved by #55

**Closed as completed** 2018-07-27 18:44 UTC
